const RSPGAME_VALUES = {
  ROCK: 'ROCK',
  SCISSORS: 'SCISSORS',
  PAPER: 'PAPER',
};

const RSPGAME_WINS = new Map([
  [RSPGAME_VALUES.ROCK, RSPGAME_VALUES.SCISSORS],
  [RSPGAME_VALUES.SCISSORS, RSPGAME_VALUES.PAPER],
  [RSPGAME_VALUES.PAPER, RSPGAME_VALUES.ROCK],
]);

const RSPGAME_RESULT_OPTIONS = {
  TIE: 'TIE',
  USER_WIN: 'USER_WIN',
  COMPUTER_WIN: 'COMPUTER_WIN',
};

module.exports = {
  RSPGAME_VALUES,
  RSPGAME_WINS,
  RSPGAME_RESULT_OPTIONS,
};
